<?php
/**
 * UploadRequest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Deeparteffects\Client
 * @author   Swaagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Deep Art Effects
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2017-02-10T16:24:46Z
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Deeparteffects\Client\Model;

use \ArrayAccess;

/**
 * UploadRequest Class Doc Comment
 *
 * @category    Class
 * @package     Deeparteffects\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class UploadRequest implements ArrayAccess
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      * @var string
      */
    protected static $swaggerModelName = 'UploadRequest';

    /**
      * Array of property to type mappings. Used for (de)serialization
      * @var string[]
      */
    protected static $swaggerTypes = [
        'style_id' => 'string',
        'image_base64_encoded' => 'string',
        'image_size' => 'int',
        'partner_id' => 'string',
        'optimize_for_print' => 'bool'
    ];

    public static function swaggerTypes()
    {
        return self::$swaggerTypes;
    }

    /**
     * Array of attributes where the key is the local name, and the value is the original name
     * @var string[]
     */
    protected static $attributeMap = [
        'style_id' => 'styleId',
        'image_base64_encoded' => 'imageBase64Encoded',
        'image_size' => 'imageSize',
        'partner_id' => 'partnerId',
        'optimize_for_print' => 'optimizeForPrint'
    ];


    /**
     * Array of attributes to setter functions (for deserialization of responses)
     * @var string[]
     */
    protected static $setters = [
        'style_id' => 'setStyleId',
        'image_base64_encoded' => 'setImageBase64Encoded',
        'image_size' => 'setImageSize',
        'partner_id' => 'setPartnerId',
        'optimize_for_print' => 'setOptimizeForPrint'
    ];


    /**
     * Array of attributes to getter functions (for serialization of requests)
     * @var string[]
     */
    protected static $getters = [
        'style_id' => 'getStyleId',
        'image_base64_encoded' => 'getImageBase64Encoded',
        'image_size' => 'getImageSize',
        'partner_id' => 'getPartnerId',
        'optimize_for_print' => 'getOptimizeForPrint'
    ];

    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    public static function setters()
    {
        return self::$setters;
    }

    public static function getters()
    {
        return self::$getters;
    }

    

    

    /**
     * Associative array for storing property values
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     * @param mixed[] $data Associated array of property values initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['style_id'] = isset($data['style_id']) ? $data['style_id'] : null;
        $this->container['image_base64_encoded'] = isset($data['image_base64_encoded']) ? $data['image_base64_encoded'] : null;
        $this->container['image_size'] = isset($data['image_size']) ? $data['image_size'] : null;
        $this->container['partner_id'] = isset($data['partner_id']) ? $data['partner_id'] : null;
        $this->container['optimize_for_print'] = isset($data['optimize_for_print']) ? $data['optimize_for_print'] : null;
    }

    /**
     * show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalid_properties = [];

        return $invalid_properties;
    }

    /**
     * validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {

        return true;
    }


    /**
     * Gets style_id
     * @return string
     */
    public function getStyleId()
    {
        return $this->container['style_id'];
    }

    /**
     * Sets style_id
     * @param string $style_id The unique identifier for a style
     * @return $this
     */
    public function setStyleId($style_id)
    {
        $this->container['style_id'] = $style_id;

        return $this;
    }

    /**
     * Gets image_base64_encoded
     * @return string
     */
    public function getImageBase64Encoded()
    {
        return $this->container['image_base64_encoded'];
    }

    /**
     * Sets image_base64_encoded
     * @param string $image_base64_encoded Base64 decoded image
     * @return $this
     */
    public function setImageBase64Encoded($image_base64_encoded)
    {
        $this->container['image_base64_encoded'] = $image_base64_encoded;

        return $this;
    }

    /**
     * Gets image_size
     * @return int
     */
    public function getImageSize()
    {
        return $this->container['image_size'];
    }

    /**
     * Sets image_size
     * @param int $image_size Image size in px. Picture will be resized for processing.
     * @return $this
     */
    public function setImageSize($image_size)
    {
        $this->container['image_size'] = $image_size;

        return $this;
    }

    /**
     * Gets partner_id
     * @return string
     */
    public function getPartnerId()
    {
        return $this->container['partner_id'];
    }

    /**
     * Sets partner_id
     * @param string $partner_id The unique identifier for a partner with dedicated api access.
     * @return $this
     */
    public function setPartnerId($partner_id)
    {
        $this->container['partner_id'] = $partner_id;

        return $this;
    }

    /**
     * Gets optimize_for_print
     * @return bool
     */
    public function getOptimizeForPrint()
    {
        return $this->container['optimize_for_print'];
    }

    /**
     * Sets optimize_for_print
     * @param bool $optimize_for_print Use this flag to get an artwork optimized for print.
     * @return $this
     */
    public function setOptimizeForPrint($optimize_for_print)
    {
        $this->container['optimize_for_print'] = $optimize_for_print;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     * @param  integer $offset Offset
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     * @param  integer $offset Offset
     * @return mixed
     */
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     * @param  integer $offset Offset
     * @param  mixed   $value  Value to be set
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     * @param  integer $offset Offset
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) { // use JSON pretty print
            return json_encode(\Deeparteffects\Client\ObjectSerializer::sanitizeForSerialization($this), JSON_PRETTY_PRINT);
        }

        return json_encode(\Deeparteffects\Client\ObjectSerializer::sanitizeForSerialization($this));
    }
}


