<?php
/**
 * UploadRequestTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Deeparteffects\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Deep Art Effects
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2017-02-10T16:24:46Z
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Deeparteffects\Client;

/**
 * UploadRequestTest Class Doc Comment
 *
 * @category    Class */
// * @description UploadRequest
/**
 * @package     Deeparteffects\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class UploadRequestTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {

    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {

    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {

    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {

    }

    /**
     * Test "UploadRequest"
     */
    public function testUploadRequest()
    {

    }

    /**
     * Test attribute "style_id"
     */
    public function testPropertyStyleId()
    {

    }

    /**
     * Test attribute "image_base64_encoded"
     */
    public function testPropertyImageBase64Encoded()
    {

    }

    /**
     * Test attribute "image_size"
     */
    public function testPropertyImageSize()
    {

    }

    /**
     * Test attribute "partner_id"
     */
    public function testPropertyPartnerId()
    {

    }

    /**
     * Test attribute "optimize_for_print"
     */
    public function testPropertyOptimizeForPrint()
    {

    }

}
