<?php
/**
 * DefaultApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Deeparteffects\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Deep Art Effects
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2017-02-10T16:24:46Z
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Deeparteffects\Client;

use \Deeparteffects\Client\Configuration;
use \Deeparteffects\Client\ApiClient;
use \Deeparteffects\Client\ApiException;
use \Deeparteffects\Client\ObjectSerializer;

/**
 * DefaultApiTest Class Doc Comment
 *
 * @category Class
 * @package  Deeparteffects\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class DefaultApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {

    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {

    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {

    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {

    }

    /**
     * Test case for resultGet
     *
     * .
     *
     */
    public function testResultGet()
    {

    }

    /**
     * Test case for resultOptions
     *
     * .
     *
     */
    public function testResultOptions()
    {

    }

    /**
     * Test case for stylesGet
     *
     * .
     *
     */
    public function testStylesGet()
    {

    }

    /**
     * Test case for stylesOptions
     *
     * .
     *
     */
    public function testStylesOptions()
    {

    }

    /**
     * Test case for uploadOptions
     *
     * .
     *
     */
    public function testUploadOptions()
    {

    }

    /**
     * Test case for uploadPost
     *
     * .
     *
     */
    public function testUploadPost()
    {

    }

}
